export type TBoxProps = {
  display?: string;
  position?: 'fixed' | 'absolute' | 'sticky' | 'static' | 'relative';
  top?: number | string;
  right?: number | string;
  bottom?: number | string;
  left?: number | string;
  flex?: number;
  flexDirection?: 'row' | 'column' | 'row-reverse' | 'column-reverse';
  flexFlow?: string;
  gap?: number | string;
  alignItems?: string;
  justifyContent?: string;
  width?: number | string;
  minWidth?: number | string;
  height?: number | string;
  minHeight?: number | string;
  color?: string;
  bgColor?: string;
  boxShadow?: string;
  margin?: number | string;
  padding?: number | string;
  borderColor?: string;
  borderWidth?: number | string;
  borderRadius?: number | string;
  borderStyle?: 'solid' | 'dashed' | 'dotted';
  zIndex?: number;
};
